#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/shell-roboshop"
SCRIPT_NAME=$( echo $0 | cut -d "." -f1 )
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log" # /var/log/shell-script/16-logs.log

mkdir -p $LOGS_FOLDER
echo "Script started executed at: $(date)" | tee -a $LOG_FILE

SOURCE_DIR=/home/ec2-user/app-logs  #Path to check files.
FILES_TO_DELETE=$(find $SOURCE_DIR -name “*.log” -type -f -mtime +14)
if [ ! -d SOURCE_DIR ]; then 
    echo -e "ERROR: $SOURCE_DIR  does not exist"
    exit 1 
fi






